package com.project.message.component;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class MessageCreator {
    public List<String> getListOfMessages() {
        List<String> list = new ArrayList<>();

        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id1\",\"appSystemID\": \"appSys_id1\"},\"task\":{\"id\":\"task_id1\",\"type\":\"task_type1\",\"status\":\"status1\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id1\",\"type\":\"doc_type1\",\"name\":\"doc_name1\",\"size\":1},{\"id\":\"doc_id21\",\"type\":\"doc_type21\",\"name\":\"doc_name21\",\"size\":21}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code1\",\"message\":\"message1\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id2\",\"appSystemID\": \"appSys_id2\"},\"task\":{\"id\":\"task_id2\",\"type\":\"task_type2\",\"status\":\"status2\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id2\",\"type\":\"doc_type2\",\"name\":\"doc_name2\",\"size\":2},{\"id\":\"doc_id22\",\"type\":\"doc_type22\",\"name\":\"doc_name22\",\"size\":22}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":null}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":null},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code3\",\"message\":\"message3\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":null,\"appSystemID\": \"appSys_id4\"},\"task\":{\"id\":\"task_id4\",\"type\":\"task_type4\",\"status\":\"status4\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id4\",\"type\":\"doc_type4\",\"name\":\"doc_name4\",\"size\":4},{\"id\":\"doc_id24\",\"type\":\"doc_type24\",\"name\":\"doc_name24\",\"size\":24}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code4\",\"message\":\"message4\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id5\",\"appSystemID\": null},\"task\":{\"id\":\"task_id5\",\"type\":\"task_type5\",\"status\":\"status5\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id5\",\"type\":\"doc_type5\",\"name\":\"doc_name5\",\"size\":5},{\"id\":\"doc_id25\",\"type\":\"doc_type25\",\"name\":\"doc_name25\",\"size\":25}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code5\",\"message\":\"message5\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id6\",\"appSystemID\": \"appSys_id6\"},\"task\":{\"id\":null,\"type\":\"task_type6\",\"status\":\"status6\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id6\",\"type\":\"doc_type6\",\"name\":\"doc_name6\",\"size\":6},{\"id\":\"doc_id26\",\"type\":\"doc_type26\",\"name\":\"doc_name26\",\"size\":26}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code6\",\"message\":\"message6\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id7\",\"appSystemID\": \"appSys_id7\"},\"task\":{\"id\":\"task_id7\",\"type\":null,\"status\":\"status7\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id7\",\"type\":\"doc_type7\",\"name\":\"doc_name7\",\"size\":7},{\"id\":\"doc_id27\",\"type\":\"doc_type27\",\"name\":\"doc_name27\",\"size\":27}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code7\",\"message\":\"message7\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id8\",\"appSystemID\": \"appSys_id8\"},\"task\":{\"id\":\"task_id8\",\"type\":\"task_type8\",\"status\":null,\"documentList\":{\"documentList\":[{\"id\":\"doc_id8\",\"type\":\"doc_type8\",\"name\":\"doc_name8\",\"size\":8},{\"id\":\"doc_id28\",\"type\":\"doc_type28\",\"name\":\"doc_name28\",\"size\":28}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code8\",\"message\":\"message8\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id9\",\"appSystemID\": \"appSys_id9\"},\"task\":{\"id\":\"task_id9\",\"type\":\"task_type9\",\"status\":\"status9\",\"documentList\":{\"documentList\":[{\"id\":null,\"type\":\"doc_type9\",\"name\":\"doc_name9\",\"size\":9},{\"id\":\"doc_id29\",\"type\":\"doc_type29\",\"name\":\"doc_name29\",\"size\":29}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code9\",\"message\":\"message9\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id10\",\"appSystemID\": \"appSys_id10\"},\"task\":{\"id\":\"task_id10\",\"type\":\"task_type10\",\"status\":\"status10\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id10\",\"type\":null,\"name\":\"doc_name10\",\"size\":10},{\"id\":\"doc_id30\",\"type\":\"doc_type30\",\"name\":\"doc_name30\",\"size\":30}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code10\",\"message\":\"message10\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id11\",\"appSystemID\": \"appSys_id11\"},\"task\":{\"id\":\"task_id11\",\"type\":\"task_type11\",\"status\":\"status11\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id11\",\"type\":\"doc_type11\",\"name\":null,\"size\":11},{\"id\":\"doc_id31\",\"type\":\"doc_type31\",\"name\":\"doc_name31\",\"size\":31}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code11\",\"message\":\"message11\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id12\",\"appSystemID\": \"appSys_id12\"},\"task\":{\"id\":\"task_id12\",\"type\":\"task_type12\",\"status\":\"status12\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id12\",\"type\":\"doc_type12\",\"name\":\"doc_name12\",\"size\":null},{\"id\":\"doc_id32\",\"type\":\"doc_type32\",\"name\":\"doc_name32\",\"size\":32}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code12\",\"message\":\"message12\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id13\",\"appSystemID\": \"appSys_id13\"},\"task\":{\"id\":\"task_id13\",\"type\":\"task_type13\",\"status\":\"status13\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id13\",\"type\":\"doc_type13\",\"name\":\"doc_name13\",\"size\":13},{\"id\":null,\"type\":\"doc_type33\",\"name\":\"doc_name33\",\"size\":33}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code13\",\"message\":\"message13\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id14\",\"appSystemID\": \"appSys_id14\"},\"task\":{\"id\":\"task_id14\",\"type\":\"task_type14\",\"status\":\"status14\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id14\",\"type\":\"doc_type14\",\"name\":\"doc_name14\",\"size\":14},{\"id\":null,\"type\":\"doc_type34\",\"name\":null,\"size\":34}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code14\",\"message\":\"message14\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id15\",\"appSystemID\": \"appSys_id15\"},\"task\":{\"id\":\"task_id15\",\"type\":\"task_type15\",\"status\":\"status15\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id15\",\"type\":\"doc_type15\",\"name\":\"doc_name15\",\"size\":15},{\"id\":\"doc_id35\",\"type\":null,\"name\":\"doc_name35\",\"size\":35}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code15\",\"message\":\"message15\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id16\",\"appSystemID\": \"appSys_id16\"},\"task\":{\"id\":\"task_id16\",\"type\":\"task_type16\",\"status\":\"status16\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id16\",\"type\":\"doc_type16\",\"name\":\"doc_name16\",\"size\":16},{\"id\":\"doc_id36\",\"type\":\"doc_type36\",\"name\":\"doc_name36\",\"size\":null}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code16\",\"message\":\"message16\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id17\",\"appSystemID\": \"appSys_id17\"},\"task\":{\"id\":\"task_id17\",\"type\":\"task_type17\",\"status\":\"status17\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id17\",\"type\":\"doc_type17\",\"name\":\"doc_name17\",\"size\":17},{\"id\":\"doc_id37\",\"type\":\"doc_type37\",\"name\":\"doc_name37\",\"size\":37}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":null,\"message\":\"message17\"}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id18\",\"appSystemID\": \"appSys_id18\"},\"task\":{\"id\":\"task_id18\",\"type\":\"task_type18\",\"status\":\"status18\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id18\",\"type\":\"doc_type18\",\"name\":\"doc_name18\",\"size\":18},{\"id\":\"doc_id38\",\"type\":\"doc_type38\",\"name\":\"doc_name38\",\"size\":38}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code18\",\"message\":null}}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id19\",\"appSystemID\": \"appSys_id19\"},\"task\":{\"id\":\"task_id19\",\"type\":\"task_type19\",\"status\":\"status19\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id19\",\"type\":\"doc_type19\",\"name\":\"doc_name19\",\"size\":19},{\"id\":\"doc_id39\",\"type\":\"doc_type39\",\"name\":\"doc_name39\",\"size\":39}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":null}}}");
        list.add("{\"messageBody\":{\"sendSignTaskRequest\":{\"customerIdInfo\":{\"customerID\":\"cust_id20\",\"appSystemID\": \"appSys_id20\"},\"task\":{\"id\":\"task_id20\",\"type\":\"task_type20\",\"status\":\"status20\",\"documentList\":{\"documentList\":[{\"id\":\"doc_id20\",\"type\":\"doc_type20\",\"name\":\"doc_name20\",\"size\":20},{\"id\":\"doc_id40\",\"type\":\"doc_type40\",\"name\":\"doc_name40\",\"size\":40},{\"id\":\"doc_id41\",\"type\":\"doc_type41\",\"name\":\"doc_name41\",\"size\":41}}]}}}},\"messageInfo\":{\"sendSignTaskResponse\":{\"resultInfo\":{\"code\":\"code20\",\"message\":\"message20\"}}}}");

        return list;
    }
}
